### ISSUE TITLE
installation using pybombs with gnuradio 3.8

### ISSUE THREAD

**Issue by hirokun2016** [dl1ksv/gr-ax25#14]
Hi,
   I pulled the 3.8 version and installed using pybombs. However, I have an error message. Can somebody help me on this?

[ 62%] Building CXX object swig/CMakeFiles/afsk_swig.dir/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx.o
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_afsk1200_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:5204:50: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >’ and ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’})
       result = gr::afsk::afsk1200::make(arg1,arg2);
                                                  ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::afsk1200>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::afsk1200>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’} to ‘const std::shared_ptr<gr::afsk::afsk1200>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:5214:117: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::afsk1200>&’}
 afsk1200::sptr(static_cast< const gr::afsk::afsk1200::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__afsk1200_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_afsk1200_sptr_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:5455:39: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >’ and ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’})
       result = (*arg1)->make(arg2,arg3);
                                       ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::afsk1200>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::afsk1200>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::afsk1200::sptr’ {aka ‘boost::shared_ptr<gr::afsk::afsk1200>’} to ‘const std::shared_ptr<gr::afsk::afsk1200>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:5465:117: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::afsk1200> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::afsk1200>&’}
 afsk1200::sptr(static_cast< const gr::afsk::afsk1200::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__afsk1200_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_ax25decode_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:8589:52: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >’ and ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’})
       result = gr::afsk::ax25decode::make(arg1,arg2);
                                                    ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::ax25decode>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::ax25decode>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’} to ‘const std::shared_ptr<gr::afsk::ax25decode>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:8599:121: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::ax25decode>&’}
 decode::sptr(static_cast< const gr::afsk::ax25decode::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__ax25decode_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_ax25decode_sptr_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:8840:39: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >’ and ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’})
       result = (*arg1)->make(arg2,arg3);
                                       ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::ax25decode>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::ax25decode>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::ax25decode::sptr’ {aka ‘boost::shared_ptr<gr::afsk::ax25decode>’} to ‘const std::shared_ptr<gr::afsk::ax25decode>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:8850:121: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::ax25decode> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::ax25decode>&’}
 decode::sptr(static_cast< const gr::afsk::ax25decode::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__ax25decode_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_aprs2inet_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:11972:51: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >’ and ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’})
       result = gr::afsk::aprs2inet::make(arg1,arg2);
                                                   ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::aprs2inet>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::aprs2inet>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’} to ‘const std::shared_ptr<gr::afsk::aprs2inet>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:11982:119: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::aprs2inet>&’}
 rs2inet::sptr(static_cast< const gr::afsk::aprs2inet::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__aprs2inet_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_aprs2inet_sptr_make(PyObject*, PyObject*, PyObject*)’:
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:12221:39: error: no match for ‘operator=’ (operand types are ‘SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >’ and ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’})
       result = (*arg1)->make(arg2,arg3);
                                       ^
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const SwigValueWrapper<T>&) [with T = std::shared_ptr<gr::afsk::aprs2inet>]’
   SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:32:21: note:   no known conversion for argument 1 from ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’} to ‘const SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note: candidate: ‘SwigValueWrapper<T>& SwigValueWrapper<T>::operator=(const T&) [with T = std::shared_ptr<gr::afsk::aprs2inet>]’
   SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
                     ^~~~~~~~
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:36:21: note:   no known conversion for argument 1 from ‘gr::afsk::aprs2inet::sptr’ {aka ‘boost::shared_ptr<gr::afsk::aprs2inet>’} to ‘const std::shared_ptr<gr::afsk::aprs2inet>&’
/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:12231:119: error: invalid static_cast from type ‘SwigValueWrapper<std::shared_ptr<gr::afsk::aprs2inet> >’ to type ‘const sptr&’ {aka ‘const boost::shared_ptr<gr::afsk::aprs2inet>&’}
 rs2inet::sptr(static_cast< const gr::afsk::aprs2inet::sptr& >(result))), SWIGTYPE_p_std__shared_ptrT_gr__afsk__aprs2inet_t, SWIG_POINTER_OWN |  0 );
                                                                     ^

/home/pi/prefix-3.8/src/gr-ax25/build/swig/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx:1191:89: note: in definition of macro ‘SWIG_NewPointerObj’
 terObj(ptr, type, flags)            SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
                                                                     ^~~

make[2]: *** [swig/CMakeFiles/afsk_swig.dir/build.make:63: swig/CMakeFiles/afsk_swig.dir/CMakeFiles/afsk_swig.dir/afsk_swigPYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:327: swig/CMakeFiles/afsk_swig.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[ERROR] Build failed. See output above for error messages.
[ERROR] Problem occurred while building package gr-ax25:
[ERROR] Build failed.
[ERROR] Error rebuilding package gr-ax25. Aborting.

**Comment by dl1ksv** [comment]
Sorry, but I did not write the receipe for the pyboms install, so I can't give you any hit what's going wrong. Perhaps there is a version mismatch between gnuradio and gr-ax25.
