### ISSUE TITLE
make install fails in pybombs due to module path not being set?

### ISSUE THREAD

**Issue by muaddib1984** [dl1ksv/gr-ax25#18]
i'm on a fresh pybombs install of gnuradio maint-3.8
i made the changes you sited here #17 and the build is fine, but make install fails with:

`CMake Error at lib/cmake_install.cmake:111 (file):
  file cannot create directory: /gr-display.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  cmake_install.cmake:52 (include)
`

I think this is due to CMAKE_MODULES_DIR not being set. Since its empty, the path defaults to just /gr-display instead of /path/inside/pybombs/env/gr-display.

**Comment by dl1ksv** [comment]
Sorry , as I'm not familiar with pybombs, I can't give you any advice.

But what I can say:
The error messages has nothing to do with the setting of CMAKE_MODULES_DIR.
This is a location where cmake can find additional cmake modules.

The message says, that it can't create a directory as the root priviliges are missing.

Why don't you just follow the README?

By the way: Are you trying to install gr-ax25 or gr-display ?

**Comment by muaddib1984** [comment]
i'm installing both, but my question was regarding gr-ax25. I'm installing gr-display separately for the APRS demo flowgraph.
Just so you know, it works fine outside of pybombs. 
There's a pybombs recipe for gr-ax25 which I assumed (incorrectly) that you contributed. 
Running the install as per usual works, but you have to run sudo make install. In pybombs you don't run as root due to it being a self contained user-space environment. Unfortunately, in your gnuradio 3.8 branch CMakeLists.txt [here ](https://github.com/dl1ksv/gr-ax25/blob/6589f635c5b48ca3c220f79658a0754a50488f15/CMakeLists.txt#L86-L101) CMAKE_MODULES_DIR resolves to nothing, therefore it tries to create a directory (/gr-display) in your / directory:
`99 SET(GR_CMAKE_DIR        ${CMAKE_MODULES_DIR}/gr-display)`


Please note however that in master [here](https://github.com/dl1ksv/gr-ax25/blob/619304f5fb8cce38bbd4fa5b0d128a7ad4e0666b/CMakeLists.txt#L79-L83) you've defined CMAKE_MODULES_DIR
`include(GrPlatform) #define LIB_SUFFIX`

`if(NOT CMAKE_MODULES_DIR)`
`  set(CMAKE_MODULES_DIR lib${LIB_SUFFIX}/cmake)`
`endif(NOT CMAKE_MODULES_DIR)`

Adding that bit to the CMakeLists.txt in the gnuradio3.8 branch means that it will find the appropriate directory inside the pybombs environment. 

sorry if the verbosity here is overkill, but i wanted to articulate that it does have to do with cmake trying to create a directory WAY outside of a project space due to an empty variable. 
anyways, i got it working so i'm a happy camper. 
thanks for the prompt responses.

**Comment by dl1ksv** [comment]
You are right, line 99 is buggy.
It should read 
SET(GR_CMAKE_DIR ${CMAKE_MODULES_DIR}/ax25)

But I'm not sure , if this solves your problem.

What is the result of

gnuradio-config-info --prefix

**Comment by muaddib1984** [comment]
i started over with a fresh build due to upgrade issues from ubuntu 18 to ubuntu 20
i'll let you know as soon as my prefix finishes building. 
i think its important to have the set commands for GR_CMAKE_DIR in your gr3.9 branch added to the 3.8 cmake, but i'll confirm once i get my new build setup.
