### ISSUE TITLE
Problem Installation 

### ISSUE THREAD

**Issue by jp-polito** [dl1ksv/gr-ax25#19]
After executing the command sudo cmake install 

This problem appears:

CMake Error at python/cmake_install.cmake:45 (file):
  file INSTALL cannot find "/home/jp/Área de
  Trabalho/gr-ax25-3.9.0/build/python/__init__.pyc": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:50 (include)

make: *** [Makefile:86: install] Erro 1

**Comment by dl1ksv** [comment]
There must be something wrong with your build process.
cmake_install.cmake does not tries to install init.pyc but \__init__.py , \__init__.pyc, \__init__.pyo and the build process does not
require init.py but \__init__.py

**Comment by jp-polito** [comment]
Thanks to answer!
I tried again to install AX.25 and presented this information, I believe it is installed correct?

jp@jp-pc:~/Downloads/gr-ax25-master/build$ sudo make install
[ 22%] Built target gnuradio-ax25
[ 33%] Built target ax25_qa_afsk1200.cc
[ 44%] Built target ax25_qa_aprs2inet.cc
[ 55%] Built target ax25_qa_ax25decode.cc
[ 55%] Built target pygen_apps_9a6dd
[ 66%] Built target pygen_python_e8f8c
[ 72%] Built target ax25_docstrings
[100%] Built target ax25_python
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/share/gnuradio/lib/cmake/ax25/ax25Config.cmake
-- Up-to-date: /usr/share/gnuradio/include/ax25/api.h
-- Up-to-date: /usr/share/gnuradio/include/ax25/afsk1200.h
-- Up-to-date: /usr/share/gnuradio/include/ax25/aprs2inet.h
-- Up-to-date: /usr/share/gnuradio/include/ax25/ax25decode.h
-- Up-to-date: /usr/share/gnuradio/lib/x86_64-linux-gnu/libgnuradio-ax25.so.v1.0-compat-xxx-xunknown
-- Up-to-date: /usr/share/gnuradio/lib/x86_64-linux-gnu/libgnuradio-ax25.so.1.0.0git
-- Up-to-date: /usr/share/gnuradio/lib/x86_64-linux-gnu/libgnuradio-ax25.so
-- Up-to-date: /usr/share/gnuradio/lib/cmake/ax25/gnuradio-ax25Targets.cmake
-- Up-to-date: /usr/share/gnuradio/lib/cmake/ax25/gnuradio-ax25Targets-release.cmake
-- Up-to-date: /usr/share/gnuradio/lib/cmake/ax25/gnuradio-ax25Config.cmake
-- Up-to-date: /usr/share/gnuradio/lib/python3/dist-packages/ax25/__init__.py
-- Up-to-date: /usr/share/gnuradio/lib/python3/dist-packages/ax25/__init__.pyc
-- Up-to-date: /usr/share/gnuradio/lib/python3/dist-packages/ax25/__init__.pyo
-- Up-to-date: /usr/share/gnuradio/lib/python3/dist-packages/ax25/ax25_python.cpython-38-x86_64-linux-gnu.so
-- Up-to-date: /usr/share/gnuradio/share/gnuradio/grc/blocks/ax25_afsk1200.block.yml
-- Up-to-date: /usr/share/gnuradio/share/gnuradio/grc/blocks/ax25_aprs2inet.block.yml
-- Up-to-date: /usr/share/gnuradio/share/gnuradio/grc/blocks/ax25_ax25decode.block.yml


But in GnuRadio the blocks don't appear.

**Comment by dl1ksv** [comment]
Your output is misleading, as the __ are missing in the names of the init files.
Where do you expect gr_ax25 blocks to appear in gnuradio ? The yml files  are installed. What are you missing?
The output from cmake command would be interesting. The output of the install looks OK.

**Comment by jp-polito** [comment]
Keep investigating that I noticed they were installed in another folder, I don't know why but created a different folder. After checking the output I moved the blocks to the /blocks folder and it worked! Thank you for your help!
Installation was here:
Up-to-date: /usr/share/gnuradio/share/gnuradio/grc/blocks/ax25_ax25decode.block.yml
But the correct this is
/usr/share/gnuradio/grc/blocks/

Possibly when installing cmake there was an error.

Thanks to answer!

**Comment by dl1ksv** [comment]
/usr/share/gnuradio/share/gnuradio/grc/blocks/ is the correct path if gnuradio is located at /usr/share/gnuradio.
This path works on my system!
What is the result of

gnuradio-config-info --prefix

Maybe the global_blocks_path is not properly set in
~/.gnuradio/config.conf
